### ISSUE TITLE
rewrite ca please

### ISSUE THREAD

**Issue by linustouchtips** [olliem5/past#2]
the ca very bad. it not place on dirt, I died 4 times then baby rage. why not make ca like obamahack >:(

**Comment by olliem5** [comment]
i will add obamahack ca and allow dirt placements for you

**Comment by linustouchtips** [comment]
yay!

**Comment by notperry1234567890** [comment]
still waiting for this very epic update

**Comment by xcc8** [comment]
[an actual vid of a 1.16 ca placing on other blocks](https://www.youtube.com/watch?v=oHg5SJYRHA0)
