### ISSUE TITLE
Hey! I just want to recommend some improvements.

### ISSUE THREAD

**Issue by BoonoBoi** [olliem5/past#8]
This is an amazing client! it's one of the best I've seen for crystal PVP even at default settings. I just recommend adding things like nametag to see the enemy's health, armor, and anything like that to see what your enemy is doing. I also recommend some auto armor. Otherwise, it's a very great client and maybe you should add some more modules so that it improves! I think this client has great potential and I hope you keep working on it!

**Comment by olliem5** [comment]
I might pick this back up in the future, but it's unlikely. This project was never meant to stick around, and most of the code is very dated and not really worth the time & effort to fix. Thanks for the feedback!

**Comment by LittleDraily** [comment]
Past rewrite how when maybe
